// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0EHs3fiytPSPrxAvlcfQ2BsZ4TSpRdRo',
    appId: '1:21334425002:web:b411cc558fc7713e3d7fd3',
    messagingSenderId: '21334425002',
    projectId: 'my-portfolio-78ae4',
    authDomain: 'my-portfolio-78ae4.firebaseapp.com',
    storageBucket: 'my-portfolio-78ae4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7J3Upm5hn2B6k8Hc81eyxX8RiAqv-TUo',
    appId: '1:21334425002:android:1eac36ec61c5d4853d7fd3',
    messagingSenderId: '21334425002',
    projectId: 'my-portfolio-78ae4',
    storageBucket: 'my-portfolio-78ae4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD057Z0e7AjMz37b3RmYxvi-98axJNSiSo',
    appId: '1:21334425002:ios:4127badf8b70b01f3d7fd3',
    messagingSenderId: '21334425002',
    projectId: 'my-portfolio-78ae4',
    storageBucket: 'my-portfolio-78ae4.firebasestorage.app',
    iosBundleId: 'com.example.adShopPos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD057Z0e7AjMz37b3RmYxvi-98axJNSiSo',
    appId: '1:21334425002:ios:4127badf8b70b01f3d7fd3',
    messagingSenderId: '21334425002',
    projectId: 'my-portfolio-78ae4',
    storageBucket: 'my-portfolio-78ae4.firebasestorage.app',
    iosBundleId: 'com.example.adShopPos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1lsBp_TPSLcDMWlz04uFjfy290D7wbjE',
    appId: '1:21334425002:web:af194bdf5bdde47b3d7fd3',
    messagingSenderId: '21334425002',
    projectId: 'my-portfolio-78ae4',
    authDomain: 'my-portfolio-78ae4.firebaseapp.com',
    storageBucket: 'my-portfolio-78ae4.firebasestorage.app',
  );
}
